name: themed_color_palette
description: A code generator to create a themed color palette from a yaml file.
repository: https://github.com/ValentinVignal/theme_color_palette
issue_tracker: https://github.com/ValentinVignal/theme_color_palette/issues
version: 0.4.2
dependencies:
  build: ^2.5.4
  dart_style: ^3.1.1
  pub_semver: ^2.2.0
  yaml: ^3.1.3

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
