name: themed_color_palette
description: A code generator to create a themed color palette from a yaml file.
repository: https://github.com/ValentinVignal/theme_color_palette
issue_tracker: https://github.com/ValentinVignal/theme_color_palette/issues
version: 0.3.4
dependencies:
  build: ^2.2.1
  yaml: ^3.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
