name: Lints

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Code Analyze
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        # cSpell:ignore subosito
        uses: subosito/flutter-action@v2
      - run: dart pub get
      - run: dart analyze

      - name: Analyze dart code
        uses: ValentinVignal/action-dart-analyze@v1.1
