name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        # cSpell:ignore subosito
        uses: subosito/flutter-action@v2
      - run: dart pub get
      - run: dart pub global activate coverage
      - name: Run the tests
        run: dart pub global run coverage:test_with_coverage
      - run: flutter test --coverage
        working-directory: example

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
